#!/usr/bin/env python3
"""
techblog-agent - Agent Logic
Generated by masumi init

This file contains your agent's business logic.
Implement your agentic behavior in the process_job function.
"""
import os
from masumi import run, Config
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Define agent logic
async def process_job(identifier_from_purchaser: str, input_data: dict):
    """
    Process a job - implement your agentic behavior here
    
    Args:
        identifier_from_purchaser: Identifier from the purchaser
        input_data: Input data matching INPUT_SCHEMA
    
    Returns:
        Result of processing
    """
    # Process input
    text = input_data.get("text", "")
    
    # Example: Human-in-the-loop - request approval before processing
    # This demonstrates how to pause execution and request human input
    from masumi.hitl import request_input
    
    # Request approval (this will pause execution until input is provided)
    # The job status will be set to 'awaiting_input' and execution will wait
    # until someone calls the /provide_input endpoint
    approval_data = await request_input(
        {
            "input_data": [
                {
                    "id": "approve",
                    "type": "boolean",
                    "name": "Approve Processing",
                    "data": {
                        "description": f"Do you want to process: {text}?"
                    }
                }
            ]
        },
        message="Please approve this processing request"
    )
    
    # Check if approval was granted
    if not approval_data.get("approve", False):
        return "Processing was not approved"
    
    # Continue with processing after approval
    result = f"Processed: {text}"
    
    return result

