#!/usr/bin/env python3
"""
techblog-agent - Main Entry Point
Generated by masumi init

This is the entry point for your Masumi agent.
Run this file to start the agent server.
"""
# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

from masumi import run
from agent import process_job

# Define input schema
INPUT_SCHEMA = {
    "input_data": [
        {
            "id": "text",
            "type": "string",
            "name": "Text Input"
        }
    ]
}

# Main entry point
if __name__ == "__main__":
    # Config and identifiers loaded from environment variables
    # Default mode is API - use --standalone flag to run standalone
    run(
        start_job_handler=process_job,
        input_schema_handler=INPUT_SCHEMA
        # config, agent_identifier, network loaded from env vars automatically
    )
